### ISSUE TITLE
[VOTE] Do not create single line method used only once

### ISSUE THREAD

**Issue by mdumoulin** [shoppingflux/coding-style-php#11]
### Summary

When a single line private method is only used once inside a class, remove it.

That kind of codes have some drawback :

- Add more line than necessary in class
- Force to navigate in the class to find information

#### Not valid
```php
<?php
namespace ShoppingFeed\Channel\Domain;

class Channel
{
    public function update(ChannelOwnerUpdate $configuration): void
    {
        $this->setContact($configuration->getContact());

        if ($configuration->hasTemplate()) {
            $this->updateTemplate($configuration->getTemplate());
        }
    }

    private function setContact(ChannelContact $contact): void
    {
        $this->contact = $contact;
    }

    private function updateTemplate(ChannelTemplate $template): void
    {
        $template->applyOn($this->fields);
    }
}
```

#### Valid

```php
<?php
namespace ShoppingFeed\Channel\Domain;

class Channel
{
    public function update(ChannelOwnerUpdate $configuration): void
    {
        $this->contact = $configuration->getContact();

        if ($configuration->hasTemplate()) {
            $configuration->getTemplate()->applyOn($this->fields);
        }
    }
}
```

### Rule declaration

I'm not sure, we can add an automatic check around this rule. If we cannot, I propose to create a recommendation section for this kind of rules.

**Comment by ddattee** [comment]
I'm not sure about this rule.

I kinda prefer to split in small methods because I find that often it clarifi "bigger" methods and for me that is reason enough to split into two methods.
In a getter/setter case I would say ok but if the private method contains even a small amount of logic I would say it is apropriate to split.
Also for the readability of the code I often found it is more readable with a private method than with everything in one method.

I've worked a lot in env where bigger method was the standard and it rapidly became unmanageable.

**Comment by ronan-gloo** [comment]
As i agree with the template uses, i'm less confortable with the contact example.
Object should provide guaranties about their own **invariants**, and, if $contact property have to be an instance of `ChannelContact`, mean even refuse NULL, this part of the **invariants** of the channel is now delegated to the `ChannelOwnerUpdate` objet.

Given the case of `$configuration->getContact()` allow to return null, because things change, if the channel require a `ChannelContact`, change from  $configuration break $channel.

Worse than that, unit test for `Channel` will not fail if you dont remember about updating them by your own : they was wrote when `ChannelContact` was a mandatory output value for `$configuration->getContact()`, and you was not able to cover the NULL case. With a setter, UT pass also but it will fail at run time, and prevent models to be persisted in inconsistent state.

Well, i'm not saying that "we should always use setter", but sometimes it matters or may save our ass, despite the fact they not look valuable in first place 😃
